import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Portfólio | Lucas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-stone-200 dark:bg-darkBlue text-midnightBlue dark:text-slateGray min-h-screen flex flex-col">
        <Header />

        <main className="pb-16 shrink grow basis-0">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
